- name: good first issue
  color: '#7057ff'
  description: Denotes an issue ready for a new contributor, according to the "help wanted" guidelines.
- name: help wanted
  color: '#006b75'
  description: Denotes an issue that needs help from a contributor. Must meet "help wanted" guidelines.
- name: do-not-merge
  color: '#e11d21'
  description: Indicates that a PR should not be merged.

- name: area/api
  color: '#0052cc'
  description: Indicates an issue on API area.
- name: area/controller
  color: '#0052cc'
  description: Issues or PRs related to controller code.
- name: area/dependency
  color: '#0052cc'
  description: Issues or PRs related to dependency changes.
- name: area/operator
  color: '#0052cc'
  description: Issues or PRs related to operator code.

- name: kind/bug
  color: '#e11d21'
  description: Categorizes issue or PR as related to a bug.
- name: kind/documentation
  color: '#c7def8'
  description: Categorizes issue or PR as related to documentation.
- name: kind/feature
  color: '#c7def8'
  description: Categorizes issue or PR as related to a new feature.
- name: kind/support
  color: '#d455d0'
  description: Categorizes issue or PR as a support question.
