[package]
name = "metapod"
version = "0.0.0"
authors = ["Mateusz Urbanek <mateusz.urbanek.98@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[dependencies]
